/* PARA GERAR AS TABELAS USE O ATRIBUTO HIBERNATE.GENERATE_DLL=TRUE EM APPLICATION.PROPERTIES */

/* CRIA O USUARIO ADMIN COM A SENHA 101010*/

INSERT INTO TB_USUARIO (ID, EMAIL, NAME, PASSWORD, ADMIN) VALUES (1 , 'admin@email.com', 'Administrador do Sistema', '6d071901727aec1ba6d8e2497ef5b709', true);
INSERT INTO TB_PERFIL (ID, NOME, ADMIN) VALUES (1, 'Perfil Admin', true);
INSERT INTO TB_USUARIO_PERFIL (USUARIO_ID, PERFIL_ID) VALUES (1, 1);
INSERT INTO TB_PERFIL_ROLES (PERFIL_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO TB_PERFIL_ROLES (PERFIL_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO TB_PERFIL_ROLES (PERFIL_ID, ROLE_ID) VALUES (1, 3);

/***************************************************************************************************************************************************
   
AS ROLES DO SISTEMA(ROLESENUM --> TB_ROLE) SÃO INSERIDAS E ATUALIZADAS AUTOMATICAMENTE PELA CLASSE APPSTART AO INICIAR A APLICACAO PELA PRIMEIRA VEZ

****************************************************************************************************************************************************/

/*CONSULTA PERFIS USUARIOS*/
SELECT U.NAME NOME_USUARIO, P.NOME PERFIS_ASSOCIADOS
FROM TB_PERFIL P, TB_USUARIO U, TB_USUARIO_PERFIL UP
WHERE  U.ID = UP.USUARIO_ID
AND UP.PERFIL_ID = P.ID;

/*CONSULTA PERMISSOES PERFIS*/
SELECT P.NOME PERFIL, R.NOME ROLE_ASSOCIADA, R.DESCRICAO DESCRICAO_ROLE
  FROM TB_PERFIL P, TB_ROLE R, TB_PERFIL_ROLES PR
 WHERE P.ID = PR.PERFIL_ID
   AND PR.ROLE_ID = R.ID;
   
/* DELETES POR ORDEM 
  
   DELETE FROM TB_PERFIL_ROLES;
   DELETE FROM TB_ROLE; 
   DELETE FROM TB_USUARIO_PERFIL;
   DELETE FROM TB_PERFIL;
   DELETE FROM TB_USUARIO; 
   
  */